### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/recursos.osweekends.com#2]
Logo para el proyecto

**Comment by ggcarlosr** [comment]
Especificamente que necesitan en cuanto a imagen, estoy interesado en realizar la contribucion.

**Comment by ggcarlosr** [comment]
Good evening, I would like to know if you want to change the identity of the application and be able to contribute to a more fresh and striking image

**Comment by Jorgeural** [comment]
Buenas Carlos! muchas gracias por prestarter a hacer el logo! el proyecto está en una fase muy temprana, y el domingo nos juntaremos a seguir decidiendo temas, y por donde avanzar, en cuanto tengamos una idea más clara te escribo nuevamente ;)

**Comment by ggcarlosr** [comment]
Gracias por responder estare atento a sus requerimientos y asi poder contribuir con ustedes.

**Comment by ggcarlosr** [comment]
Buen dia, como estan ya se podra colaborar con el logotipo para su proyecto?? cual seria sus requerimientos, estoy muy interesado en colaborar.
