### ISSUE TITLE
Filtro formateo de texto longitud máxima

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/recursos.osweekends.com#32]
Crear un filtro de vue que permita formatear un texto a una longitud deseada, y añadile puntos suspensivos.

En principio esta funcionalidad se va a utilizar en el listado de recurso (src/components/resources/ListResources) , de modo que en las fichas solo se vean los X primeros caracteres de la descripción. y una vez se acceda al detalle del recurso ya aparezca la descripción completa. 

Los filtros aceptan parametros, quizá estaría bien poder pasarle por parametro el numero de caracteres que deseamos que se muestre, de modod que pueda ser reutilizable en otros contextos de la aplicación.

Doc vue: https://vuejs.org/v2/guide/filters.html

**Comment by Xexuline** [comment]
fixed
