### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/recursos.osweekends.com#33]
Deplay de entorno Dev.

Firebase tiene una opción de hosting. 

Tener el entorno dev en una url para facilitar el acceso.

Posteriormente se creará una bbdd especifica para las pruebas de usuario independiente del entorno dev

**Comment by trigoporres** [comment]
Para hacer un deploy en firebase con vue desde la consola ejecutar los siguientes comandos desde la carpeta donde se encuentre el proyecto:

1. firebase login (usuario y contraseña de firebase)
2. firebase init: selecionamos la opcion de hosting. En nuestro proyecto se creara un archivo firebase.json
3. En firebase.json debemos tener:
              "hosting": {
                      "public": "./dist",
               }
4.ejecutamos desde terminal npm run build
5.Por ultimo firebase deploy
