### ISSUE TITLE
Decidir stack tecnológico

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/recursos.osweekends.com#4]
Dicusión para decidir el stack a utilizar 

- [x] MongoDB -  solución cloud? 
- [X] NodeJs - Todos de acuerdo
- [x] Express vs Pillars
- [X] VUE - Todos de acuerdo

**Comment by jonasync** [comment]
En cuanto al Stack y según lo que hemos ido diciendo, no se que os parecería tirar de:
Vuejs + Nodejs + (PillarJS?) + Mongodb

En cuanto al CSS, tiramos con Bootstrap para simplificar temas de grid

No sé si me dejo algo 🤔

**Comment by trigoporres** [comment]
Yo esto de acuerdo en usar: Vuejs + node + pillar + mongodb.

Siempre llegado el momento se puede iterar y cambiar este stack

**Comment by Jorgeural** [comment]
Finalmente vamos a iniciar el proyecto con Node, Express, Mongo y Vue. 

Es posible que más adelante se refactorice y se implemente Pillarsjs
