### ISSUE TITLE
Completar BACKLOG

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/recursos.osweekends.com#5]
Completar fichero BACKLOG.md

   - [x] Roadmap
- [x] Backlog producto
- [x] Backlog técnico

**Comment by jonasync** [comment]
Lanzo lista de propuestas de funcionalidades posibles, según lo que se ha hablado por Slack. 
Listo todo por tener una foto general y luego vemos que metemos en el MVP así como cuales vamos desarrollando en cada sprint

#### Backlog producto
> MVP
- [ ] Pagina estática: *Landing explicando el proyecto con enlace a OSW y quizás los recursos más votados y últimos recursos aprobados (en MVP estarán hardcoded)*
- [ ] Vista de listado de recursos
- [ ] Tipos de recursos *(charla, curso, tutorial, articulo, documentación...)*
- [ ] Categorías de recursos *Molaría que fuese abierto a todo tipo de recurso y jugar con 2 niveles de categoría. Por ejemplo 'Desarrollo' y dentro de esta (js, react, html, scrum)* 
- [ ] Etiquetas de recursos
> Futuros Sprints
- [ ] Filtrado
- [ ] Buscador
- [ ] Sugerir un nuevo recurso
- [ ] Registrarse y autenticación en la aplicación.
- [ ] Validación de nuevo recurso por parte de los usuarios (filtros automáticos y karma)
- [ ] Valoran recurso
- [ ] Reportar recurso
- [ ] Comentar recurso
- [ ] Lista de favoritos
- [ ] Karma de usuarios / Logros

No sé si me dejo algo.. se abre la veda!

**Comment by Jorgeural** [comment]
Me gusta lo de las categorías a 2 niveles, no cerrarlo al mundo del desarrollo y que pueda haber recursos de otras cosas.

Perdonad mis habilidades prototipando xD pero algo sí de inicio tenía en mente. 

Pagina de inicio comentando el proyecto, mencionar la comunidad y link al repo para posibles contributos

![inicio](https://user-images.githubusercontent.com/16987747/37651386-3c5e3f32-2c38-11e8-9c3e-3e5ef0b5c137.png)

Pinchas en la pestaña eventos y ya ves el grid (se incluirá filtros etc etc )
![recursos](https://user-images.githubusercontent.com/16987747/37651387-3c7bb88c-2c38-11e8-9ac0-ba327f478d99.png)

**Comment by jonasync** [comment]
@Jorgeural creo MVP puede servir, de todos modos no metas colores aún. Yo creo que ya pensaremos UX/UI en la siguiente vuelta
