### ISSUE TITLE
Login desde componente listResources 

### ISSUE THREAD

**Issue by trigoporres** [OSWeekends/recursos.osweekends.com#62]
Me he dado cuenta que sin estar logeado y acceder a la lista de recursos, si me logeo desde esa ruta no aparece el boton de añadir recurso.
![captura de pantalla 2018-06-02 a las 20 25 20](https://user-images.githubusercontent.com/22293570/40879621-2661827a-66a3-11e8-8fa7-e866efe9f960.png)

**Comment by NachoRV** [comment]
se tenia confirmar con isloggin de los mapGetters
